# Generated by Django 4.2.1 on 2023-05-19 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargeName', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Civilian',
            fields=[
                ('civId', models.IntegerField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('imageProfileURL', models.CharField(max_length=1000)),
                ('detailsProfile', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('repId', models.IntegerField(primary_key=True, serialize=False)),
                ('reportName', models.CharField(max_length=100)),
                ('detailsReport', models.CharField(max_length=1000)),
                ('dateCreated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Arrested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isWarrant', models.BooleanField()),
                ('civId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.civilian')),
                ('repId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.report')),
            ],
        ),
    ]
