# Generated by Django 4.2.1 on 2023-05-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Civilian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civId', models.IntegerField()),
                ('fullName', models.CharField(max_length=100)),
                ('imageProfileURL', models.CharField(max_length=100)),
                ('detailsProfile', models.CharField(max_length=1000)),
            ],
        ),
    ]
