# Generated by Django 4.2.1 on 2023-05-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian',
            name='imageProfileURL',
            field=models.CharField(max_length=1000),
        ),
    ]
