# Generated by Django 4.2.1 on 2023-05-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian',
            name='detailsProfile',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='civilian',
            name='imageProfileURL',
            field=models.CharField(default='https://static.vecteezy.com/ti/vettori-gratis/p3/2158565-avatar-profilo-rosa-neon-icona-muro-mattoni-sfondo-rosa-neon-icona-vettore-vettoriale.jpg', max_length=1000),
        ),
    ]
